### ISSUE TITLE
TypeError Cannot assign string to property verbb\workflow\models\Settings::$editorNotesRequired of type array

### ISSUE THREAD

**Issue by danieladarve** [engram-design/Workflow#207]
### Describe the bug

Getting the following error after upgrading craftcms v3 to v4 and upgrading verbb/workflow from 1.7.6 to 2.0.9.

Removing and reinstalling the plugin brings back the issue.

```
TypeError: Cannot assign string to property verbb\workflow\models\Settings::$editorNotesRequired of type array in /Users/dev/project/vendor/yiisoft/yii2/base/Model.php:742
Stack trace:
#0 /Users/dev/project/vendor/craftcms/cms/src/base/Model.php(220): yii\base\Model->setAttributes(Array, false)
#1 /Users/dev/project/vendor/craftcms/cms/src/base/Plugin.php(193): craft\base\Model->setAttributes(Array, false)
#2 /Users/dev/project/vendor/yiisoft/yii2/base/Component.php(180): craft\base\Plugin->setSettings(Array)
#3 /Users/dev/project/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('settings', Array)
#4 /Users/dev/project/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(verbb\workflow\Workflow), Array)
#5 /Users/dev/project/vendor/yiisoft/yii2/base/Module.php(161): yii\base\BaseObject->__construct(Array)
#6 /Users/dev/project/vendor/craftcms/cms/src/base/Plugin.php(122): yii\base\Module->__construct('workflow', Object(craft\web\Application), Array)
#7 [internal function]: craft\base\Plugin->__construct('workflow', Object(craft\web\Application), Array)
#8 /Users/dev/project/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#9 /Users/dev/project/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('verbb\\workflow\\...', Array, Array)
#10 /Users/dev/project/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('verbb\\workflow\\...', Array, Array)
#11 /Users/dev/project/vendor/craftcms/cms/src/Craft.php(59): yii\BaseYii::createObject(Array, Array)
#12 /Users/dev/project/vendor/craftcms/cms/src/services/Plugins.php(943): Craft::createObject(Array, Array)
#13 /Users/dev/project/vendor/craftcms/cms/src/services/Plugins.php(228): craft\services\Plugins->createPlugin('workflow', Array)
#14 /Users/dev/project/vendor/craftcms/cms/src/base/ApplicationTrait.php(1649): craft\services\Plugins->loadPlugins()
#15 /Users/dev/project/vendor/craftcms/cms/src/web/Application.php(111): craft\web\Application->_postInit()
#16 /Users/dev/project/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#17 /Users/dev/project/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#18 [internal function]: yii\base\Application->__construct(Array)
#19 /Users/dev/project/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#20 /Users/dev/project/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#21 /Users/dev/project/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#22 /Users/dev/project/vendor/craftcms/cms/src/Craft.php(59): yii\BaseYii::createObject(Array, Array)
#23 /Users/dev/project/vendor/craftcms/cms/bootstrap/bootstrap.php(250): Craft::createObject(Array)
#24 /Users/dev/project/vendor/craftcms/cms/bootstrap/web.php(40): require('/Users/danielad...')
#25 /Users/dev/project/web/index.php(20): require('/Users/danielad...')
#26 /Users/dev/.composer/vendor/laravel/valet/server.php(110): require('/Users/dev...')
#27 {main}
```

### Steps to reproduce

1. follow guide in https://craftcms.com/docs/4.x/upgrade.html
2. upgrade verbb/workflow from 1.7.6 to 2.0.9

### Craft CMS version

4.8.0

### Plugin version

2.0.9

### Multi-site?

No

**Comment by danieladarve** [comment]
Solved by deleting the settings section for worflow in the proyect.yml config which was:

```
  workflow:
    edition: standard
    enabled: true
    licenseKey: XXXXXXXXXXXXXXXXXXXXX
    schemaVersion: 2.1.6
    settings:
      editorNotesRequired: '1'
      editorNotifications: '1'
      editorNotificationsOptions:
        - replyTo
      editorUserGroup: 425cccf0-1692-4fe6-8525-f15663772a2c # Editors
      enabledSections: '*'
      publisherNotesRequired: ''
      publisherNotifications: '1'
      publisherUserGroup: 5c6452a4-a5a1-4f65-8231-a75168281230 # Publishers
      selectedPublishers: '*'
```

new config is:
```
  workflow:
    edition: standard
    enabled: true
    licenseKey: XXXXXXXXXXXXXXXXXXXXX
    schemaVersion: 2.5.0
    settings:
      editorNotesRequired:
        __assoc__:
          -
            - 8400cac9-ee6f-4033-951c-74724f26cf88 # Website
            - '1'
      editorNotifications: true
      editorNotificationsOptions:
        - replyTo
      editorUserGroup:
        __assoc__:
          -
            - 8400cac9-ee6f-4033-951c-74724f26cf88 # Website
            - 425cccf0-1692-4fe6-8525-f15663772a2c # Editors
      enabledSections: '*'
      lockDraftSubmissions: true
      publishedAuthorNotifications: false
      publisherNotesRequired:
        __assoc__:
          -
            - 8400cac9-ee6f-4033-951c-74724f26cf88 # Website
            - ''
      publisherNotifications: true
      publisherUserGroup:
        __assoc__:
          -
            - 8400cac9-ee6f-4033-951c-74724f26cf88 # Website
            - 5c6452a4-a5a1-4f65-8231-a75168281230 # Publishers
      reviewerApprovalNotifications: false
      reviewerNotifications: true
      reviewerUserGroups:
        __assoc__:
          -
            - 8400cac9-ee6f-4033-951c-74724f26cf88 # Website
            - ''
      selectedPublishers: '*'
```

Looks like the upgrade didnt upgrade the settings
